# Generated by Django 6.0.6 on 2026-06-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('Suave', 'Suave'), ('Seco', 'Seco'), ('Branco', 'Branco'), ('Tinto', 'Tinto')], max_length=20)),
                ('disponivel', models.BooleanField(default=False)),
            ],
        ),
    ]
